Fix AudioContext options type error
- Changed from List [] to Set {} for AVAudioSessionOptions
- Fixes compilation error: 'List<AVAudioSessionOptions>' can't be assigned to 'Set<AVAudioSessionOptions>'
- Resolves macOS build failure